[build]
  command = "composer install --no-dev"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PHP_VERSION = "8.1"

# Handle all requests with index.php
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for PHP files
[[headers]]
  for = "/*.php"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
