[build]
  command = "composer install --no-dev"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.1"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  node_bundler = "esbuild"
